#include "Meme.h"
#include <iostream>
#include <string>

void Meme::fortnite(void)
{
	std::cout << "⠀⠀⠀⠀⣀⣤							   " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⠿⣶							  " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⣿⣀							  " << std::endl;
	std::cout << "⠀⠀⠀⣶⣶⣿⠿⠛⣶							 " << std::endl;
	std::cout << "⠤⣀⠛⣿⣿⣿⣿⣿⣿⣭⣿⣤						" << std::endl;
	std::cout << "⠒⠀⠀⠀⠉⣿⣿⣿⣿⠀⠀⠉⣀						" << std::endl;
	std::cout << "⠀⠤⣤⣤⣀⣿⣿⣿⣿⣀⠀⠀⣿						" << std::endl;
	std::cout << "⠀⠀⠛⣿⣿⣿⣿⣿⣿⣿⣭⣶⠉						" << std::endl;
	std::cout << "⠀⠀⠀⠤⣿⣿⣿⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⣭⣿⣿⣿⠀⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⣉⣿⣿⠿⠀⠿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⣿⠀⠀⠀⣿⣿⣤						 " << std::endl;
	std::cout << "⠀⠀⠀⣀⣿⣿⠀⠀⠀⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⣿⣿⣿⠀⠀⠀⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⣿⣿⠛⠀⠀⠀⠉⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠉⣿⠀⠀⠀⠀⠀⠛⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⣛⠀⠀⠀⠀⠀⠀⠛⠿⠿⠿					" << std::endl;
	std::cout << "⠀⠀⠀⠛⠛								   " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⣀⣶⣀							  " << std::endl;
	std::cout << "⠀⠀⠀⠒⣛⣭							  " << std::endl;
	std::cout << "⠀⠀⠀⣀⠿⣿⣶							  " << std::endl;
	std::cout << "⠀⣤⣿⠤⣭⣿⣿							  " << std::endl;
	std::cout << "⣤⣿⣿⣿⠛⣿⣿⠀⣀							 " << std::endl;
	std::cout << "⠀⣀⠤⣿⣿⣶⣤⣒⣛							 " << std::endl;
	std::cout << "⠉⠀⣀⣿⣿⣿⣿⣭⠉							 " << std::endl;
	std::cout << "⠀⠀⣭⣿⣿⠿⠿⣿							 " << std::endl;
	std::cout << "⠀⣶⣿⣿⠛⠀⣿⣿							 " << std::endl;
	std::cout << "⣤⣿⣿⠉⠤⣿⣿⠿							 " << std::endl;
	std::cout << "⣿⣿⠛⠀⠿⣿⣿							  " << std::endl;
	std::cout << "⣿⣿⣤⠀⣿⣿⠿							  " << std::endl;
	std::cout << "⠀⣿⣿⣶⠀⣿⣿⣶							 " << std::endl;
	std::cout << "⠀⠀⠛⣿⠀⠿⣿⣿							  " << std::endl;
	std::cout << "⠀⠀⠀⣉⣿⠀⣿⣿							  " << std::endl;
	std::cout << "⠀⠶⣶⠿⠛⠀⠉⣿							 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣀⣿							  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣶⣿⠿							  " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⠶⠀⠀⣀⣀					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣶⣿⣿⣿⣿⣿⣿				   " << std::endl;
	std::cout << "⠀⠀⣀⣶⣤⣤⠿⠶⠿⠿⠿⣿⣿⣿⣉⣿⣿				  " << std::endl;
	std::cout << "⠿⣉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⣤⣿⣿⣿⣀			   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿⣶⣤			   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⣿⣿⠿⣛⣿			   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠛⣿⣿⣿⣿			   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⠿⠀⣿⣿⣿⠛			   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⣿⣿⣿			   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠿⠿⣿⠀⠀⣿⣶				" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠛⠀⠀⣿⣿⣶				" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⠤				" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠿⣿				" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿				" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣀				" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿				" << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⣀								   " << std::endl;
	std::cout << "⠀⠿⣿⣿⣀								  " << std::endl;
	std::cout << "⠀⠉⣿⣿⣀								  " << std::endl;
	std::cout << "⠀⠀⠛⣿⣭⣀⣀⣤							 " << std::endl;
	std::cout << "⠀⠀⣿⣿⣿⣿⣿⠛⠿⣶⣀						" << std::endl;
	std::cout << "⠀⣿⣿⣿⣿⣿⣿⠀⠀⠀⣉⣶						" << std::endl;
	std::cout << "⠀⠀⠉⣿⣿⣿⣿⣀⠀⠀⣿⠉						" << std::endl;
	std::cout << "⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⣀⣿⣿⣿⣿⣿⣿⣿⣿⠿						" << std::endl;
	std::cout << "⠀⣿⣿⣿⠿⠉⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⣿⣿⠿⠀⠀⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⣶⣿⣿⠀⠀⠀⠀⣿⣿⣿						 " << std::endl;
	std::cout << "⠛⣿⣿⣀⠀⠀⠀⣿⣿⣿⣿⣶⣀						" << std::endl;
	std::cout << "⠀⣿⣿⠉⠀⠀⠀⠉⠉⠉⠛⠛⠿⣿⣶				   " << std::endl;
	std::cout << "⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿					 " << std::endl;
	std::cout << "⠀⠀⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉					 " << std::endl;
	std::cout << "⣀⣶⣿⠛								   " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣿⣿⣿⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣤⣿⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣶⣿⣿⣿⣶⣶⣤⣶⣶⠶⠛⠉⠉⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣤⣿⠿⣿⣿⣿⣿⣿⠀⠀⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠛⣿⣤⣤⣀⣤⠿⠉⠀⠉⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠉⠉⠉⠉⠉⠀⠀⠀⠀⠉⣿⣿⣿⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀	 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀	  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣛⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⠛⠿⣿⣿⣿⣶⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣿⠛⠉⠀⠀⠀⠛⠿⣿⣿⣶⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl; 
	std::cout << "⠀⠀⠀⠀⠀⠀⣿⣀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⣶⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠛⠿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⣿⠿⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀" << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣤⣶⣶							  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣀⣀						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣀⣶⣿⣿⣿⣿⣿⣿						" << std::endl;
	std::cout << "⣤⣶⣀⠿⠶⣿⣿⣿⠿⣿⣿⣿⣿					   " << std::endl;
	std::cout << "⠉⠿⣿⣿⠿⠛⠉⠀⣿⣿⣿⣿⣿					   " << std::endl;
	std::cout << "⠀⠀⠉⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣤⣤					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣤⣶⣿⣿⣿⣿⣿⣿					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣀⣿⣿⣿⣿⣿⠿⣿⣿⣿⣿				   " << std::endl;
	std::cout << "⠀⠀⠀⠀⣀⣿⣿⣿⠿⠉⠀⠀⣿⣿⣿⣿				   " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⣿⠿⠉⠀⠀⠀⠀⠿⣿⣿⠛					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠛⣿⣿⣀⠀⠀⠀⠀⠀⣿⣿⣀					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⠀⠿⣿⣿					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠉⣿⣿⠀⠀⠀⠀⠀⠀⠉⣿					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⣀⣿					 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣀⣿⣿							  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠤⣿⠿⠿⠿							 " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⠀⣀								   " << std::endl;
	std::cout << "⠀⠀⣶⣿⠿⠀⠀⠀⣀⠀⣤⣤						 " << std::endl;
	std::cout << "⠀⣶⣿⠀⠀⠀⠀⣿⣿⣿⠛⠛⠿⣤⣀				   " << std::endl;
	std::cout << "⣶⣿⣤⣤⣤⣤⣤⣿⣿⣿⣀⣤⣶⣭⣿⣶⣀				  " << std::endl;
	std::cout << "⠉⠉⠉⠛⠛⠿⣿⣿⣿⣿⣿⣿⣿⠛⠛⠿⠿				  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⠿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣭⣿⣿⣿⣿⣿					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⣿⣿⣿⣿					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⠿					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⠿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣿⠛⠿⣿⣤					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⠀⠀⠀⣿⣿⣤					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⣶⣿⠛⠉					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⠀⠀⠉					 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉						  " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣶⣿⣶							  " << std::endl;
	std::cout << "⠀⠀⠀⣤⣤⣤⣿⣿⣿							 " << std::endl;
	std::cout << "⠀⠀⣶⣿⣿⣿⣿⣿⣿⣿⣶						" << std::endl;
	std::cout << "⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿						" << std::endl;
	std::cout << "⠀⠀⣿⣉⣿⣿⣿⣿⣉⠉⣿⣶						" << std::endl;
	std::cout << "⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⠿⣿						" << std::endl;
	std::cout << "⠀⣤⣿⣿⣿⣿⣿⣿⣿⠿⠀⣿⣶						" << std::endl;
	std::cout << "⣤⣿⠿⣿⣿⣿⣿⣿⠿⠀⠀⣿⣿⣤				   " << std::endl;
	std::cout << "⠉⠉⠀⣿⣿⣿⣿⣿⠀⠀⠒⠛⠿⠿⠿				   " << std::endl;
	std::cout << "⠀⠀⠀⠉⣿⣿⣿⠀⠀⠀⠀⠀⠀⠉					 " << std::endl;
	std::cout << "⠀⠀⠀⣿⣿⣿⣿⣿⣶							 " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⠉⠿⣿⣿							 " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⣤⠀⠛⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⣶⣿⠀⠀⠀⣿⣶						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣭⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⠉						 " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣶						  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣀⣀⠀⣶⣿⣿⠶						 " << std::endl;
	std::cout << "⣶⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣤					   " << std::endl;
	std::cout << "⠀⠉⠶⣶⣀⣿⣿⣿⣿⣿⣿⣿⠿⣿⣤⣀				  " << std::endl;
	std::cout << "⠀⠀⠀⣿⣿⠿⠉⣿⣿⣿⣿⣭⠀⠶⠿⠿				   " << std::endl;
	std::cout << "⠀⠀⠛⠛⠿⠀⠀⣿⣿⣿⣉⠿⣿⠶					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣤⣶⣿⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⠒						" << std::endl;
	std::cout << "⠀⠀⠀⠀⣀⣿⣿⣿⣿⣿⣿⣿						" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣿⣿⣿⠛⣭⣭⠉						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣿⣿⣭⣤⣿⠛						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠛⠿⣿⣿⣿⣭						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣿⣿⠉⠛⠿⣶⣤					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣀⣿⠀⠀⣶⣶⠿⠿⠿					" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣿⠛							  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⣭⣶							  " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣤						  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⣶⠀⠀⣀⣤⣶⣤⣉⣿⣿⣤⣀					" << std::endl;
	std::cout << "⠤⣤⣿⣤⣿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣀				  " << std::endl;
	std::cout << "⠀⠛⠿⠀⠀⠀⠀⠉⣿⣿⣿⣿⣿⠉⠛⠿⣿⣤			  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⠛⠀⠀⠀⣶⠿			   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣀⣿⣿⣿⣿⣤⠀⣿⠿				   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⣿⣿⣿⣿⣿⣿				   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠿⣿⣿⣿⣿⣿⠿⠉⠉				   " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠉⣿⣿⣿⣿⠿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠉						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣛⣿⣭⣶⣀						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠉⠛⣿					 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⣿⣿					 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣉⠀⣶⠿					 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⠿						 " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⠀⠀⠛⠿⠛						  " << std::endl;
	std::cout << "										" << std::endl;
	std::cout << "⠀⠀⠀⣶⣿⣶							  " << std::endl;
	std::cout << "⠀⠀⠀⣿⣿⣿⣀							  " << std::endl;
	std::cout << "⠀⣀⣿⣿⣿⣿⣿⣿							 " << std::endl;
	std::cout << "⣶⣿⠛⣭⣿⣿⣿⣿							 " << std::endl;
	std::cout << "⠛⠛⠛⣿⣿⣿⣿⠿							 " << std::endl;
	std::cout << "⠀⠀⠀⠀⣿⣿⣿							  " << std::endl;
	std::cout << "⠀⠀⣀⣭⣿⣿⣿⣿⣀							 " << std::endl;
	std::cout << "⠀⠤⣿⣿⣿⣿⣿⣿⠉							 " << std::endl;
	std::cout << "⠀⣿⣿⣿⣿⣿⣿⠉							 " << std::endl;
	std::cout << "⣿⣿⣿⣿⣿⣿							  " << std::endl;
	std::cout << "⣿⣿⣶⣿⣿								  " << std::endl;
	std::cout << "⠉⠛⣿⣿⣶⣤							  " << std::endl;
	std::cout << "⠀⠀⠉⠿⣿⣿⣤							  " << std::endl;
	std::cout << "⠀⠀⣀⣤⣿⣿⣿							  " << std::endl;
	std::cout << "⠀⠒⠿⠛⠉⠿⣿							  " << std::endl;
	std::cout << "⠀⠀⠀⠀⠀⣀⣿⣿							  " << std::endl;
	std::cout << "⠀⠀⠀⠀⣶⠿⠿⠛                            " << std::endl;
}